### PR TITLE
fix: Fix build script and the command output

### PR DESCRIPTION
**Pull request by xmnlab**
* Fix the build/install workflow
* Fix the command output, that should be printed in "real-time"

### CODE REVIEW

**Comment by xmnlab** [comment]
before these changes, the output was:

```
23:38 $ docker-compose build
#1 [runner internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [runner internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.35kB done
#2 DONE 0.0s

#3 [runner internal] load metadata for docker.io/library/ubuntu:23.04
#3 ...

#4 [runner auth] library/ubuntu:pull token for registry-1.docker.io
#4 DONE 0.0s

#3 [runner internal] load metadata for docker.io/library/ubuntu:23.04
#3 DONE 1.4s

#5 [runner 1/7] FROM docker.io/library/ubuntu:23.04@sha256:b5d5cddaeb8d2f150660cf8f9a1203dd450ac765e6c07630176ac6486eceaddb
#5 DONE 0.0s

#6 [runner internal] load build context
#6 transferring context: 709B 0.0s done
#6 DONE 0.0s

#7 [runner 4/7] RUN cd /home/docker && mkdir actions-runner && cd actions-runner   && echo "docker ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/docker   && chmod 0440 /etc/sudoers.d/docker   && curl -O -L https://github.com/actions/runner/releases/download/v2.306.0/actions-runner-linux-x64-2.306.0.tar.gz   && tar xzf ./actions-runner-linux-x64-2.306.0.tar.gz   && echo "b0a090336f0d0a439dac7505475a1fb822f61bbb36420c7b3b3fe6b1bdc4dbaa  actions-runner-linux-x64-2.306.0.tar.gz" | shasum -a 256 -c
#7 CACHED

#8 [runner 6/7] COPY start.sh start.sh
#8 CACHED

#9 [runner 2/7] RUN apt update -y && apt upgrade -y && useradd -m docker
#9 CACHED

#10 [runner 3/7] RUN apt install -y --no-install-recommends   curl   jq   build-essential   libssl-dev   libffi-dev   python3   python3-venv   python3-dev   python3-pip   git   sudo
#10 CACHED

#11 [runner 5/7] RUN chown -R docker ~docker && /home/docker/actions-runner/bin/installdependencies.sh
#11 CACHED

#12 [runner 7/7] RUN chmod +x start.sh
#12 CACHED

#13 [runner] exporting to image
#13 exporting layers done
#13 writing image sha256:8ef3c80ed243dd4a568f0525bc49653c23af2097299aa930029b82ace03dca35 done
#13 naming to docker.io/library/github-actions-self-hosted-runner-runner 0.0s done
#13 DONE 0.0s
```


with these changes, the output is:

```
23:38 $ docker-compose build
[+] Building 0.7s (12/12) FINISHED                                                                                                                                                         
 => [runner internal] load .dockerignore                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                       0.0s
 => [runner internal] load build definition from Dockerfile                                                                                                                           0.0s
 => => transferring dockerfile: 1.35kB                                                                                                                                                0.0s
 => [runner internal] load metadata for docker.io/library/ubuntu:23.04                                                                                                                0.5s
 => [runner 1/7] FROM docker.io/library/ubuntu:23.04@sha256:b5d5cddaeb8d2f150660cf8f9a1203dd450ac765e6c07630176ac6486eceaddb                                                          0.0s
 => [runner internal] load build context                                                                                                                                              0.0s
 => => transferring context: 30B                                                                                                                                                      0.0s
 => CACHED [runner 2/7] RUN apt update -y && apt upgrade -y && useradd -m docker                                                                                                      0.0s
 => CACHED [runner 3/7] RUN apt install -y --no-install-recommends   curl   jq   build-essential   libssl-dev   libffi-dev   python3   python3-venv   python3-dev   python3-pip   gi  0.0s
 => CACHED [runner 4/7] RUN cd /home/docker && mkdir actions-runner && cd actions-runner   && echo "docker ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/docker   && chmod 0440 /etc/sud  0.0s
 => CACHED [runner 5/7] RUN chown -R docker ~docker && /home/docker/actions-runner/bin/installdependencies.sh                                                                         0.0s
 => CACHED [runner 6/7] COPY start.sh start.sh                                                                                                                                        0.0s
 => CACHED [runner 7/7] RUN chmod +x start.sh                                                                                                                                         0.0s
 => [runner] exporting to image                                                                                                                                                       0.0s
 => => exporting layers                                                                                                                                                               0.0s
 => => writing image sha256:8ef3c80ed243dd4a568f0525bc49653c23af2097299aa930029b82ace03dca35                                                                                          0.0s
 => => naming to docker.io/library/github-actions-self-hosted-runner-runner 
```

**Comment by xmnlab** [comment]
also before the changes, the output is printed just after the whole process ... now the result is in "real-time"

**Comment by xmnlab** [comment]
@luabida I will merge this as I need this changes, but feel free to add your review here and I will address it in a follow-up PR. thanks!

**Review by luabida — COMMENTED** [review]
LGTM!

**Pull request merged**
