### PR TITLE
refactor: Improve the release workflow and allows release from the scheduler

### PR DESCRIPTION
**Pull request by xmnlab**
This PR aims to improve the release workflow and set the version of this package to the same version used by docker-compose, that means that semantic-release is not necessary anymore and needs to be removed.

### CODE REVIEW

**Comment by xmnlab** [comment]
@luabida could  you review this PR, please?

TBH, I never used this two new github actions (one for commit and the other one for release), but we will know it just when pushing that to master, I guess.

**Comment by xmnlab** [comment]
it seems that it built the correct version: https://github.com/osl-package-recipes/compose-go/pull/19/checks#step:5:9

but in the tests, it uses a different version: https://github.com/osl-package-recipes/compose-go/pull/19/checks#step:6:9

**Comment by xmnlab** [comment]
the main ci was missing the step for the installation. it is working now: https://github.com/osl-package-recipes/compose-go/actions/runs/5104715371/jobs/9175823002?pr=19#step:6:9

**Comment by luabida** [comment]
LGTM!

**Review by luabida — APPROVED** [review]

**Comment by xmnlab** [comment]
thanks for the review @luabida !

**Pull request merged**
